spring:
  config:
    import: classpath:service/wpb.yaml
  flyway:
    locations:
      - classpath:migration/wpb
      - classpath:migration/statuslist
    ignore-migration-patterns:
      - "*:missing"
      - "*:future"
  application:
    name: wpb-backend

info:
  application:
    name: EUDI-Wallet WPB backend service

challenge:
  symk-prefix: ${hsm.key-prefix}-wpb_challenge_symk
