spring:
  config:
    import: classpath:service/pns.yaml
  flyway:
    locations:
      - classpath:migration/pns
    ignore-migration-patterns:
      - "*:missing"
      - "*:future"
  application:
    name: pns-backend

info:
  application:
    name: EUDI-Wallet PNS backend service

challenge:
  symk-prefix: ${hsm.key-prefix}-pns_challenge_symk
